#!/usr/bin/env python3
"""Run AI-as-Judge evaluation on evaluation bundles.

Supports:
  - Specific bundles via --bundles PATH ...
  - Auto-discover all un-judged bundles via --all (replaces run_judge_all.sh)
  - Filter by study/dataset with --studies and --datasets
  - Force re-evaluation with --force

Uses the project's make_llm() factory for provider-agnostic model access.

Usage:
    python -m scripts.run_ai_judge --bundles outputs/ablation/AB-00/datasets/01_basics_ecommerce/evaluation_bundle.json
    python -m scripts.run_ai_judge --all --studies AB-01 AB-02
    python -m scripts.run_ai_judge --all --judge gpt-5.4-mini --force
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from dotenv import load_dotenv  # type: ignore[import]

load_dotenv(ROOT / ".env")

# ── Constants ────────────────────────────────────────────────────────────────────

BASE = Path("outputs/ablation")
DATASETS = [
    "01_basics_ecommerce",
    "02_intermediate_finance",
    "03_advanced_healthcare",
    "04_complex_manufacturing",
    "05_edgecases_incomplete",
    "06_edgecases_legacy",
]
STUDY_IDS = [f"AB-{i:02d}" for i in range(1, 21)]


# ── Core ─────────────────────────────────────────────────────────────────────────


def load_prompt() -> str:
    prompt_file = ROOT / "docs" / "AI_JUDGE_PROMPT.md"
    if not prompt_file.exists():
        raise FileNotFoundError(f"AI_JUDGE_PROMPT.md not found at {prompt_file}")
    return prompt_file.read_text(encoding="utf-8")


def evaluate_bundle(bundle_path: Path, judge_model: str, system_prompt: str) -> str:
    """Call the AI judge for a single evaluation bundle using make_llm()."""
    from langchain_core.messages import HumanMessage, SystemMessage  # type: ignore[import]

    from src.config.llm_factory import make_llm  # noqa: PLC0415

    bundle_text = bundle_path.read_text(encoding="utf-8")
    user_msg = (
        "Please evaluate the following evaluation_bundle.json according to the rubric "
        "and output format described in the system prompt.\n\n"
        f"```json\n{bundle_text}\n```"
    )

    print(f"  Calling {judge_model} for {bundle_path.parent.name}...", flush=True)
    llm = make_llm(judge_model, temperature=0.0, max_tokens=8000, role="ai_judge")
    response = llm.invoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_msg),
    ])
    return response.content or "" # type: ignore


def _bundle_meta(bundle_path: Path) -> dict:
    with open(bundle_path, encoding="utf-8") as f:
        d = json.load(f)
    meta = d.get("meta", {})
    cfg = d.get("config", {})
    qr = d.get("query_report", {})
    br = d.get("builder_report", {})
    return {
        "label": f"{meta.get('study_id', '?')}/{meta.get('dataset_id', '?')}",
        "grounded_rate": qr.get("grounded_rate", 0),
        "avg_gt_coverage": qr.get("avg_gt_coverage", 0),
        "avg_top_score": qr.get("avg_top_score", 0),
        "triplets": br.get("triplets_extracted", 0),
        "entities": br.get("entities_resolved", 0),
    }


def _discover_unjudged(
    studies: list[str] | None,
    datasets: list[str] | None,
    force: bool,
) -> list[Path]:
    """Find evaluation_bundle.json files that need judging."""
    studies = studies or STUDY_IDS
    datasets = datasets or DATASETS
    bundles: list[Path] = []

    for study in studies:
        for ds in datasets:
            bundle_path = BASE / study / ds / "evaluation_bundle.json"
            judge_path = BASE / study / ds / "ai_judge.md"
            if not bundle_path.exists():
                continue
            if not force and judge_path.exists():
                continue
            bundles.append(bundle_path)

    return bundles


def _evaluate_bundles(
    bundle_paths: list[Path],
    judge_model: str,
    system_prompt: str,
    output: Path | None,
) -> None:
    """Evaluate a list of bundles and save results."""
    bundle_metas = [_bundle_meta(p) for p in bundle_paths]
    hdr = "| Run | grounded_rate | avg_gt_coverage | avg_top_score | triplets | entities |\n"
    sep = "|-----|:---:|:---:|:---:|:---:|:---:|\n"
    rows = ""
    for m in bundle_metas:
        gt_cov = m['avg_gt_coverage']
        gt_str = f"**{gt_cov:.3f}**" if gt_cov is not None else "N/A"
        rows += (
            f"| {m['label']} | {m['grounded_rate']:.3f} | {gt_str} "
            f"| {m['avg_top_score']:.3f} | {m['triplets']} | {m['entities']} |\n"
        )

    combined_sections: list[str] = []

    if output:
        combined_sections.append(
            f"# AI-Judge Evaluation Report\n"
            f"**Generated by:** AI Judge (`{judge_model}`) using `docs/AI_JUDGE_PROMPT.md`  \n"
            f"**Date:** {date.today()}\n"
            f"\n---\n\n"
            f"## Raw Metrics Summary\n\n"
            + hdr + sep + rows + "\n---\n\n"
        )

    for bundle_path in bundle_paths:
        with open(bundle_path, encoding="utf-8") as f:
            bundle_data = json.load(f)

        meta = bundle_data.get("meta", {})
        label = f"{meta.get('study_id', '?')}/{meta.get('dataset_id', '?')}"
        print(f"\nEvaluating: {label}")

        evaluation = evaluate_bundle(bundle_path, judge_model, system_prompt)

        per_bundle_path = bundle_path.parent / "ai_judge.md"
        per_bundle_content = (
            f"# AI-Judge Evaluation: {label}\n"
            f"**Generated by:** AI Judge (`{judge_model}`) using `docs/AI_JUDGE_PROMPT.md`  \n"
            f"**Date:** {date.today()}\n\n"
            f"---\n\n"
            + evaluation
        )
        per_bundle_path.write_text(per_bundle_content, encoding="utf-8")
        print(f"  Saved: {per_bundle_path}")

        if output:
            combined_sections.append(f"# Evaluation: {label}\n\n{evaluation}\n\n---\n\n")

    if output:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text("\n".join(combined_sections), encoding="utf-8")
        print(f"\nCombined report: {output}")

    # ── Thesis CSV export for evaluated bundles ──
    try:
        from src.evaluation.thesis_export import (  # noqa: PLC0415
            export_run_csv,
            export_run_summary_csv,
        )

        for bundle_path in bundle_paths:
            with open(bundle_path, encoding="utf-8") as f:
                bd = json.load(f)
            # Reconstruct a summary-like dict from the bundle
            meta = bd.get("meta", {})
            thesis_summary = {
                "study_id": meta.get("study_id", ""),
                "dataset_id": meta.get("dataset_id", ""),
                "run_tag": meta.get("run_tag", ""),
                "timestamp": meta.get("timestamp", ""),
                "config": bd.get("config", {}),
                "builder": bd.get("builder_report", {}),
                "query": bd.get("query_report", {}),
                "per_question": bd.get("per_question", []),
                "ragas": bd.get("ragas_metrics"),
            }
            thesis_dir = bundle_path.parent / "thesis"
            export_run_csv(thesis_summary, thesis_dir)
            export_run_summary_csv(thesis_summary, thesis_dir)
        print(f"  Thesis CSVs exported for {len(bundle_paths)} bundles")
    except Exception as tex:
        print(f"  ⚠ Thesis CSV export failed (non-fatal): {tex}")


# ── CLI ─────────────────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(description="Run AI Judge on evaluation bundles")

    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--bundles", nargs="+", metavar="PATH", help="Specific evaluation_bundle.json files")
    mode.add_argument("--all", action="store_true", help="Auto-discover all un-judged bundles")

    parser.add_argument("--studies", nargs="+", metavar="AB-XX", help="Filter studies (with --all)")
    parser.add_argument("--datasets", nargs="+", metavar="DS", help="Filter datasets (with --all)")
    parser.add_argument("--output", type=Path, default=None, help="Combined output markdown")
    _default_judge = os.environ.get("JUDGE_MODEL", "gpt-5.4-mini")
    parser.add_argument("--judge", default=_default_judge, help=f"Judge model (default: {_default_judge})")
    parser.add_argument("--force", action="store_true", help="Re-evaluate even if ai_judge.md exists")
    args = parser.parse_args()

    system_prompt = load_prompt()
    print(f"Loaded AI Judge prompt ({len(system_prompt)} chars)")

    if args.all:
        bundle_paths = _discover_unjudged(args.studies, args.datasets, args.force)
        if not bundle_paths:
            print("No un-judged bundles found.")
            return
        print(f"Found {len(bundle_paths)} bundles to evaluate")
    else:
        bundle_paths = []
        missing = []
        for p in args.bundles:
            pp = Path(p)
            if pp.exists():
                bundle_paths.append(pp)
            else:
                missing.append(p)
        for m in missing:
            print(f"WARNING: not found: {m}", file=sys.stderr)

    if not bundle_paths:
        print("No bundles to evaluate.")
        return

    _evaluate_bundles(bundle_paths, args.judge, system_prompt, args.output)


if __name__ == "__main__":
    main()
