#!/usr/bin/env python3
"""
Run AI-as-Judge evaluation on one or more evaluation_bundle.json files.

Each bundle is evaluated individually and saved as ``ai_judge.md`` inside
the same directory as the bundle.  An optional combined summary report can
be written with ``--output``.

Usage:
    python scripts/run_ai_judge.py \
        --bundles outputs/ablation/AB-00/datasets/01_basics_ecommerce/evaluation_bundle.json \
                  outputs/ablation/AB-00/datasets/02_intermediate_finance/evaluation_bundle.json \
        --judge gpt-5.4-mini

    # With optional combined output:
    python scripts/run_ai_judge.py \
        --bundles ... \
        --output outputs/ablation/AB-00/judge/AI_JUDGE_REPORT.md \
        --judge gpt-5.4-mini
"""

import argparse
import json
import os
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from dotenv import load_dotenv  # noqa: E402

load_dotenv(ROOT / ".env")


def load_prompt() -> str:
    prompt_file = ROOT / "docs" / "AI_JUDGE_PROMPT.md"
    if not prompt_file.exists():
        raise FileNotFoundError(f"AI_JUDGE_PROMPT.md not found at {prompt_file}")
    return prompt_file.read_text(encoding="utf-8")


def evaluate_bundle(bundle_path: Path, judge_model: str, system_prompt: str) -> str:
    """Call the AI judge for a single evaluation bundle."""
    from openai import OpenAI

    api_key = os.environ.get("OPENAI_API_KEY") or os.environ.get("OPENROUTER_API_KEY")
    base_url = None
    if not os.environ.get("OPENAI_API_KEY") and os.environ.get("OPENROUTER_API_KEY"):
        base_url = "https://openrouter.ai/api/v1"
    client = OpenAI(api_key=api_key, base_url=base_url)

    bundle_text = bundle_path.read_text(encoding="utf-8")
    user_msg = (
        "Please evaluate the following evaluation_bundle.json according to the rubric "
        "and output format described in the system prompt.\n\n"
        f"```json\n{bundle_text}\n```"
    )

    print(f"  Calling {judge_model} for {bundle_path.parent.name}...", flush=True)
    response = client.chat.completions.create(
        model=judge_model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_msg},
        ],
        max_completion_tokens=8000,
    )
    return response.choices[0].message.content or ""


def _bundle_meta(bundle_path: Path) -> dict:
    with open(bundle_path) as f:
        d = json.load(f)
    meta = d.get("meta", {})
    cfg = d.get("config", {})
    qr = d.get("query_report", {})
    br = d.get("builder_report", {})
    return {
        "label": f"{meta.get('study_id', '?')}/{meta.get('dataset_id', '?')}",
        "reasoning_model": cfg.get("reasoning_model", "?"),
        "extraction_model": cfg.get("extraction_model", "?"),
        "grounded_rate": qr.get("grounded_rate", 0),
        "avg_gt_coverage": qr.get("avg_gt_coverage", 0),
        "avg_top_score": qr.get("avg_top_score", 0),
        "triplets": br.get("triplets_extracted", 0),
        "entities": br.get("entities_resolved", 0),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Run AI Judge on evaluation bundles")
    parser.add_argument(
        "--bundles",
        nargs="+",
        required=True,
        help="Paths to evaluation_bundle.json files",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Optional: combined output markdown file path",
    )
    parser.add_argument(
        "--judge",
        default="gpt-5.4-mini",
        help="Judge model name (default: gpt-5.4-mini)",
    )
    args = parser.parse_args()

    # Load system prompt
    system_prompt = load_prompt()
    print(f"Loaded AI Judge system prompt ({len(system_prompt)} chars)")

    bundle_paths = [Path(p) for p in args.bundles if Path(p).exists()]
    missing = [p for p in args.bundles if not Path(p).exists()]
    for p in missing:
        print(f"WARNING: bundle not found: {p}", file=sys.stderr)

    # Build summary table rows (from metadata, before calling the judge)
    bundle_metas = [_bundle_meta(p) for p in bundle_paths]
    hdr = "| Run | grounded_rate | avg_gt_coverage | avg_top_score | triplets | entities |\n"
    sep = "|-----|:---:|:---:|:---:|:---:|:---:|\n"
    rows = ""
    for m in bundle_metas:
        rows += (
            f"| {m['label']} | {m['grounded_rate']:.3f} | **{m['avg_gt_coverage']:.3f}** "
            f"| {m['avg_top_score']:.3f} | {m['triplets']} | {m['entities']} |\n"
        )

    combined_sections: list[str] = []

    if args.output:
        combined_sections.append(
            f"# AI-Judge Evaluation Report\n"
            f"**Generated by:** AI Judge (`{args.judge}`) using `docs/AI_JUDGE_PROMPT.md`  \n"
            f"**Date:** {date.today()}\n"
            f"\n---\n\n"
            f"## Raw Metrics Summary\n\n"
            + hdr + sep + rows + "\n---\n\n"
        )

    # Per-bundle evaluation
    for bundle_path in bundle_paths:
        with open(bundle_path) as f:
            bundle_data = json.load(f)

        meta = bundle_data.get("meta", {})
        label = f"{meta.get('study_id', '?')}/{meta.get('dataset_id', '?')}"
        print(f"\nEvaluating bundle: {label}")

        evaluation = evaluate_bundle(bundle_path, args.judge, system_prompt)

        # Save per-bundle file alongside the bundle itself
        per_bundle_path = bundle_path.parent / "ai_judge.md"
        per_bundle_content = (
            f"# AI-Judge Evaluation: {label}\n"
            f"**Generated by:** AI Judge (`{args.judge}`) using `docs/AI_JUDGE_PROMPT.md`  \n"
            f"**Date:** {date.today()}\n\n"
            f"---\n\n"
            + evaluation
        )
        per_bundle_path.write_text(per_bundle_content, encoding="utf-8")
        print(f"  Saved: {per_bundle_path}")

        if args.output:
            combined_sections.append(f"# Evaluation: {label}\n\n{evaluation}\n\n---\n\n")

    # Optional combined output
    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(combined_sections), encoding="utf-8")
        print(f"\nCombined report saved to: {output_path}")


if __name__ == "__main__":
    main()

