# All prompt templates centralised.
# Constants: EXTRACTION_SYSTEM, EXTRACTION_USER, ER_JUDGE_SYSTEM, ER_JUDGE_USER,
# MAPPING_SYSTEM, MAPPING_USER, ENRICHMENT_SYSTEM, ENRICHMENT_USER,
# CRITIC_SYSTEM, CRITIC_USER, REFLECTION_TEMPLATE, CYPHER_SYSTEM, CYPHER_USER,
# CYPHER_FIX_USER, ANSWER_SYSTEM, ANSWER_USER, GRADER_SYSTEM, GRADER_USER.
